---
title: "Fasteignafjöldi Sveitarfélaga"
author: 
    -   name: "Brynjólfur Gauti Guðrúnar Jónsson"
        url: "https://twitter.com/bgautijonsson"
        affiliation: "Tölfræði, Raunvísindadeild Háskóla Íslands"
        affiliation-url: "https://www.hi.is/tolfraedi_0"
date: today
format: 
    html:
        code-fold: true
        toc: true
        toc-location: right
        toc-title: Efnisyfirlit
editor: source
theme: flatly
title-block-banner: true
standalone: true
self-contained: true
---


```{r}
#| include = FALSE


library(pxweb)
library(tidyverse)
library(cowplot)
library(ggthemes)
library(scales)
library(gganimate)
```

# Gögn

```{r}
d <- read_csv2("fullbuid.csv") |> 
    pivot_longer(c(-Ár), names_to = "sveitarfelag", values_to = "fullbuid") |> 
    janitor::clean_names() |> 
    mutate(sveitarfelag = str_replace(sveitarfelag, "\\.\\.\\.[0-9]+$", "")) |> 
    inner_join(
        read_csv2("ofullbuid.csv") |> 
            pivot_longer(c(-Ár), names_to = "sveitarfelag", values_to = "ofullbuid") |> 
            janitor::clean_names() |> 
            mutate(sveitarfelag = str_replace(sveitarfelag, "\\.\\.\\.[0-9]+$", "")),
        by = c("ar", "sveitarfelag")
    )

mannfjoldi <- pxweb_get(
    url ="https://px.hagstofa.is:443/pxis/api/v1/is/Ibuar/mannfjoldi/2_byggdir/sveitarfelog/MAN02005.px", 
    query = list(
        "Sveitarfélag" = c("*"),
        "Aldur" = c("-1"),
        "Ár" = c("*"),
        "Kyn" = c("0")
    ),
    verbose = FALSE
) |> 
    as.data.frame() |> 
    as_tibble() |> 
    janitor::clean_names() |> 
    rename(mannfjoldi = mannfjoldi_eftir_sveitarfelagi_kyni_og_aldri_1_januar_1998_2022) |> 
    mutate(ar = parse_number(ar)) |> 
    filter(sveitarfelag != "Alls") |> 
    select(sveitarfelag, ar, mannfjoldi) |> 
    mutate(sveitarfelag = fct_recode(sveitarfelag,
                                     "Akureyrarkaupstaður" = "Akureyrarbær"))


d <- d |> 
    inner_join(
        mannfjoldi,
        by = c("sveitarfelag", "ar")
    )
```

# Myndir

## Fjölgun fasteigna

### Á höfðatölu

```{r, fig.asp = 0.5, fig.width = 10, out.width = "100%"}
plot_dat <- d |> 
    group_by(sveitarfelag) |> 
    mutate(nyjar_fullbunar = c(0, diff(fullbuid)) / mannfjoldi * 1000) |> 
    ungroup() |> 
    filter(ar >= 2010, ar < 2022) |> 
    mutate(label = ifelse(ar == max(ar), sveitarfelag, NA_character_),
           x = ar,
           y = nyjar_fullbunar,
           y = case_when(sveitarfelag == "Mosfellsbær" ~ y ,
                         sveitarfelag == "Kópavogsbær" ~ y,
                         sveitarfelag == "Garðabær" ~ y,
                         sveitarfelag == "Reykjavíkurborg" ~ y,
                         sveitarfelag == "Hafnarfjarðarkaupstaður" ~ y,
                         sveitarfelag == "Seltjarnarnesbær" ~ y,
                         TRUE ~ y))


p <- plot_dat |> 
    ggplot(aes(ar, nyjar_fullbunar)) +
    geom_hline(yintercept = 0, lty = 2, alpha = 0.6) +
    geom_line(data = plot_dat |> rename(svf = sveitarfelag), aes(group = svf), col = "grey50", alpha = 0.3, size = 0.5) +
    # geom_point(data = plot_dat |> rename(svf = sveitarfelag), aes(group = svf), col = "grey50", alpha = 0.5) +
    geom_line(aes(col = sveitarfelag)) +
    geom_point(aes(col = sveitarfelag)) +
    # geom_text(data = plot_dat |> group_by(sveitarfelag) |> filter(ar == max(ar)),
    #           aes(label = label, x = x, y = y, col = label), nudge_x = 0.1, hjust = 0, size = 4) +
    geom_rangeframe() +
    geom_text(data = tibble(sveitarfelag = "Mosfellsbær",
                            ar = 2014.2,
                            nyjar_fullbunar = 18.9,
                            label = "48.5"),
              aes(col = sveitarfelag, label = label), size = 3.5) +
    metR::geom_arrow(data = tibble(sveitarfelag = "Mosfellsbær",
                            x = 2014.6, y = 21.5,
                            dx = 0.35,
                            dy = 0.5),
               aes(x = x, y = y, dx = dx, dy = dy, col = sveitarfelag), size = 0.4) +
    scale_x_continuous(limits = c(2010, 2021),
                       breaks = c(2010, 2014, 2018, 2021)) +
    scale_y_continuous(labels = label_number(accuracy = 0.1),
                  breaks = c(range(plot_dat$nyjar_fullbunar), 0, 5, 15, 24.4),
                  limits = c(-1.8, 49),
                  expand = expansion()) +
    scale_colour_brewer(type = "qual", palette = "Dark2") +
    coord_cartesian(ylim = c(-1.8, 25)) +
    facet_wrap("sveitarfelag") +
    theme_tufte() +
    theme(legend.position = "none", strip.background = element_rect(fill = "grey95")) +
    labs(x = NULL,
         y = NULL,
         title = "Nýjar fullbúnar íbúðir (sér- og fjölbýli) per 1.000 manns í sveitarfélögum Höfuðborgarsvæðisins",
         caption = "Kóði og gögn: https://github.com/bgautijonsson/fasteignafjoldi")

p

ggsave(plot = p,
       filename = "nyjar_fullbunar_hofdatolu.png",
       width = 8, height = 0.5 * 8, scale = 1.3, bg = "white")
```

### Árleg breyting í íbúðum og íbúum

```{r, fig.asp = 0.5, fig.width = 10, out.width = "100%"}
p <- d |> 
    group_by(sveitarfelag) |> 
    mutate(Fasteignir =  c(1, exp(diff(log(fullbuid)))),
           Íbúar =  c(1, exp(diff(log(mannfjoldi))))) |> 
    ungroup() |> 
    select(-fullbuid, -ofullbuid, -mannfjoldi) |> 
    pivot_longer(c(-ar, -sveitarfelag)) |> 
    filter(ar >= 2010, ar < 2022) |> 
    mutate(x = ar - 0.1 + 0.2 * (name == "Fasteignir")) |> 
    ggplot(aes(ar, value)) +
    geom_hline(yintercept = 1, lty = 2, alpha = 0.6) +
    geom_area(aes(fill  = name), alpha = 0.3, position = "identity") +
    geom_line(aes(col = name)) +
    # geom_point(aes(col = name)) +
    # geom_segment(aes(col = name, xend = x, yend = 1)) +
    scale_x_continuous(breaks = c(2010, 2012, 2014, 2016, 2018, 2021)) +
    scale_y_log10(labels = function(x)  percent(x - 1),
                       expand = expansion()) +
    scale_colour_brewer(type = "qual", palette = "Set1") +
    scale_fill_brewer(type = "qual", palette = "Set1") +
    facet_wrap("sveitarfelag", nrow = 2,  scales = "free") +
    theme_half_open() +
    theme(legend.position = "top") +
    labs(title = "Árleg breyting í fjölda íbúða (sér- og fjölbýli) og íbúa í sveitarfélögum Höfuðborgarsvæðisins",
         x = NULL,
         y = NULL,
         fill= NULL,
         col = NULL)

ggsave(plot = p,
       filename = "hlutf_breyting_fasteignir_ibuar.png",
       width = 8, height = 0.5 * 8, scale = 2, bg = "white")
```

### Uppsöfnuð

```{r, fig.asp = 0.5, fig.width = 10, out.width = "100%"}
p <- d |> 
    group_by(sveitarfelag) |> 
    filter(ar >= 2010) |> 
    mutate(Fasteignir =  c(1, exp(cumsum(diff(log(fullbuid))))),
           Íbúar =  c(1, exp(cumsum(diff(log(mannfjoldi)))))) |> 
    ungroup() |> 
    select(-fullbuid, -ofullbuid, -mannfjoldi) |> 
    pivot_longer(c(-ar, -sveitarfelag)) |> 
    filter(ar >= 2010, ar < 2022) |> 
    mutate(x = ar - 0.1 + 0.2 * (name == "Fasteignir")) |> 
    ggplot(aes(ar, value)) +
    geom_hline(yintercept = 1, lty = 2, alpha = 0.6) +
    geom_area(aes(fill  = name), alpha = 0.3, position = "identity") +
    geom_line(aes(col = name)) +
    # geom_point(aes(col = name)) +
    # geom_segment(aes(col = name, xend = x, yend = 1)) +
    scale_x_continuous(breaks = c(2010, 2012, 2014, 2016, 2018, 2021)) +
    scale_y_log10(labels = function(x)  percent(x - 1),
                       expand = expansion()) +
    scale_colour_brewer(type = "qual", palette = "Set1") +
    scale_fill_brewer(type = "qual", palette = "Set1") +
    facet_wrap("sveitarfelag", nrow = 2) +
    theme_half_open() +
    theme(legend.position = "top") +
    labs(title = "Uppsöfnuð breyting í fjölda íbúða (sér- og fjölbýli) og íbúa í sveitarfélögum Höfuðborgarsvæðisins",
         x = NULL,
         y = NULL,
         fill= NULL,
         col = NULL)

p

ggsave(plot = p,
       filename = "hlutf_uppsöfnuð_breyting_fasteignir_ibuar.png",
       width = 8, height = 0.5 * 8, scale = 2, bg = "white")
```


## Fasteignafjöldi á íbúa


```{r, fig.asp = 0.5, fig.width = 10, out.width = "100%"}
plot_dat_alls <- d |> 
    filter(ar >= 2010) |> 
    group_by(ar) |> 
    summarise(fullbuid = sum(fullbuid),
              mannfjoldi = sum(mannfjoldi),
              .groups = "drop") |> 
    mutate(fullbuid_per_ibui = fullbuid / mannfjoldi * 1000,
           x = ar,
           y = fullbuid_per_ibui,
           label = "Höfuðborgarsvæðið")

plot_dat <-  d |> 
    filter(ar >= 2010) |> 
    mutate(fullbuid_per_ibui = fullbuid / mannfjoldi * 1000) |> 
    mutate(label = ifelse(ar == max(ar), sveitarfelag, NA_character_),
           x = ar,
           y = fullbuid_per_ibui,
           y = case_when(sveitarfelag == "Mosfellsbær" ~ y ,
                         sveitarfelag == "Kópavogsbær" ~ y,
                         sveitarfelag == "Garðabær" ~ y,
                         sveitarfelag == "Reykjavíkurborg" ~ y,
                         sveitarfelag == "Hafnarfjarðarkaupstaður" ~ y + 1,
                         sveitarfelag == "Seltjarnarnesbær" ~ y - 1,
                         TRUE ~ y))

p <- plot_dat |> 
    ggplot(aes(ar, fullbuid_per_ibui)) +
    geom_line(data = plot_dat_alls, col = "grey50") +
    geom_point(data = plot_dat_alls, col = "grey50") +
    geom_text(data = plot_dat_alls |>  filter(ar == max(ar)),
              aes(label = label, x = x, y = y), col = "grey50", nudge_x = 0.1, hjust = 0, size = 4) +
    geom_line(aes(col = sveitarfelag)) +
    geom_point(aes(col = sveitarfelag)) +
    geom_text(data = plot_dat |> group_by(sveitarfelag) |> filter(ar == max(ar)),
              aes(label = label, x = x, y = y, col = label), nudge_x = 0.1, hjust = 0, size = 4) +
    geom_rangeframe() +
    scale_x_continuous(limits = c(2010, 2024.3),
                       breaks = 2010:2022) +
    scale_y_log10(labels = label_number(),
                  breaks = c(range(plot_dat$fullbuid_per_ibui), 375, 400)) +
    scale_colour_brewer(type = "qual", palette = "Dark2") +
    theme_tufte() +
    theme(legend.position = "none") +
    labs(x = NULL,
         y = NULL,
         title = "Fjöldi íbúða (sér- og fjölbýli) á 1.000 íbúa í sveitarfélögum Höfuðborgarsvæðisins (2010 - 2022)",
         subtitle = "Líka borið saman við fjöldann á Höfuðborgarsvæðinu í heild",
         caption = "Kóði og gögn: https://github.com/bgautijonsson/fasteignafjoldi")

p

ggsave(plot = p,
       filename = "fasteignir_a_mannfjolda.png",
       width = 8, height = 0.5 * 8, scale = 1.3, bg = "white")
```

### Breyting frá 2010

#### Hlutfallsleg

```{r, fig.asp = 0.5, fig.width = 10, out.width = "100%"}
plot_dat_alls <- d |> 
    filter(ar >= 2010) |> 
    group_by(ar) |> 
    summarise(fullbuid = sum(fullbuid),
              mannfjoldi = sum(mannfjoldi),
              .groups = "drop") |> 
    mutate(fullbuid_per_ibui = fullbuid / mannfjoldi * 1000,
           hlutf_aukning = fullbuid_per_ibui / fullbuid_per_ibui[ar == min(ar)],
           x = ar,
           y = hlutf_aukning,
           label = "Höfuðborgarsvæðið")

plot_dat <-  d |> 
    filter(ar >= 2010) |> 
    mutate(fullbuid_per_ibui = fullbuid / mannfjoldi) |> 
    group_by(sveitarfelag) |> 
    mutate(hlutf_aukning = fullbuid_per_ibui / fullbuid_per_ibui[ar == min(ar)]) |> 
    ungroup() |> 
    mutate(label = ifelse(ar == max(ar), sveitarfelag, NA_character_),
           x = ar,
           y = hlutf_aukning,
           y = case_when(sveitarfelag == "Mosfellsbær" ~ y ,
                         sveitarfelag == "Kópavogsbær" ~ y,
                         sveitarfelag == "Garðabær" ~ y,
                         sveitarfelag == "Reykjavíkurborg" ~ y + 0.0023,
                         sveitarfelag == "Hafnarfjarðarkaupstaður" ~ y,
                         sveitarfelag == "Seltjarnarnesbær" ~ y - 0.002,
                         TRUE ~ y))

p <- plot_dat |> 
    ggplot(aes(ar, hlutf_aukning)) +
    geom_line(data = plot_dat_alls, col = "grey50") +
    geom_point(data = plot_dat_alls, col = "grey50") +
    geom_text(data = plot_dat_alls |>  filter(ar == max(ar)),
              aes(label = label, x = x, y = y), col = "grey50", nudge_x = 0.1, hjust = 0, size = 4) +
    geom_hline(yintercept = 1, lty = 2, alpha = 0.5) +
    geom_line(aes(col = sveitarfelag)) +
    geom_point(aes(col = sveitarfelag)) +
    geom_text(data = plot_dat |> group_by(sveitarfelag) |> filter(ar == max(ar)),
              aes(label = label, x = x, y = y, col = label), nudge_x = 0.1, hjust = 0, size = 4) +
    geom_rangeframe() +
    scale_x_continuous(limits = c(2010, 2024.3),
                       breaks = 2010:2022) +
    scale_y_continuous(labels = function(x) percent(x - 1),
                  breaks = c(range(plot_dat$hlutf_aukning), 0.95, 1, 1.05)) +
    scale_colour_brewer(type = "qual", palette = "Dark2") +
    theme_tufte() +
    theme(legend.position = "none") +
    labs(x = NULL,
         y = NULL,
         title = "Breyting í fjölda fasteigna á höfðatölu í sveitarfélögum höfuðborgarsvæðisins (2010 - 2022)",
         subtitle = "Líka borið saman við aukningu á Höfuðborgarsvæðinu í heild",
         caption = "Kóði og gögn: https://github.com/bgautijonsson/fasteignafjoldi")

p

ggsave(plot = p,
       filename = "fasteignir_a_mannfjolda_hlutf_aukning_2010.png",
       width = 8, height = 0.5 * 8, scale = 1.3, bg = "white")
```


### Breyting frá 2018

#### Hlutfallsleg

```{r, fig.asp = 0.5, fig.width = 10, out.width = "100%"}
plot_dat_alls <- d |> 
    filter(ar >= 2018) |> 
    group_by(ar) |> 
    summarise(fullbuid = sum(fullbuid),
              mannfjoldi = sum(mannfjoldi),
              .groups = "drop") |> 
    mutate(fullbuid_per_ibui = fullbuid / mannfjoldi * 1000,
           hlutf_aukning = fullbuid_per_ibui / fullbuid_per_ibui[ar == min(ar)],
           x = ar,
           y = hlutf_aukning - 0.001,
           label = "Höfuðborgarsvæðið")

plot_dat <-  d |> 
    filter(ar >= 2018) |> 
    mutate(fullbuid_per_ibui = fullbuid / mannfjoldi) |> 
    group_by(sveitarfelag) |> 
    mutate(hlutf_aukning = fullbuid_per_ibui / fullbuid_per_ibui[ar == min(ar)]) |> 
    ungroup() |> 
    mutate(label = ifelse(ar == max(ar), sveitarfelag, NA_character_),
           x = ar,
           y = hlutf_aukning,
           y = case_when(sveitarfelag == "Mosfellsbær" ~ y ,
                         sveitarfelag == "Kópavogsbær" ~ y - 0.003,
                         sveitarfelag == "Garðabær" ~ y,
                         sveitarfelag == "Reykjavíkurborg" ~ y + 0,
                         sveitarfelag == "Hafnarfjarðarkaupstaður" ~ y,
                         sveitarfelag == "Seltjarnarnesbær" ~ y,
                         TRUE ~ y))

p <- plot_dat |> 
    ggplot(aes(ar, hlutf_aukning)) +
    # geom_line(data = plot_dat_alls, col = "grey50") +
    # geom_point(data = plot_dat_alls, col = "grey50") +
    # geom_text(data = plot_dat_alls |>  filter(ar == max(ar)),
    #           aes(label = label, x = x, y = y), col = "grey50", nudge_x = 0.1, hjust = 0, size = 4) +
    geom_hline(yintercept = 1, lty = 2, alpha = 0.5) +
    geom_line(aes(col = sveitarfelag)) +
    geom_point(aes(col = sveitarfelag)) +
    geom_text(data = plot_dat |> group_by(sveitarfelag) |> filter(ar == max(ar)),
              aes(label = label, x = x, y = y, col = label), nudge_x = 0.1, hjust = 0, size = 4) +
    geom_rangeframe() +
    scale_x_continuous(limits = c(2018, 2022.9),
                       breaks = 2010:2022) +
    scale_y_continuous(labels = function(x) percent(x - 1),
                  breaks = c(range(plot_dat$hlutf_aukning), 0.95, 1, 1.05)) +
    scale_colour_brewer(type = "qual", palette = "Dark2") +
    theme_tufte() +
    theme(legend.position = "none") +
    labs(x = NULL,
         y = NULL,
         title = "Hlutfallsleg breyting í fjölda fasteigna á höfðatölu í sveitarfélögum höfuðborgarsvæðisins (2018 - 2022)",
         caption = "Kóði og gögn: https://github.com/bgautijonsson/fasteignafjoldi")

p

ggsave(plot = p,
       filename = "fasteignir_a_mannfjolda_hlutf_aukning_2018.png",
       width = 8, height = 0.5 * 8, scale = 1.3, bg = "white")
```

```{r, fig.asp = 0.5, fig.width = 10, out.width = "100%"}

plot_dat <-  d |> 
    filter(ar >= 2018) |> 
    mutate(fullbuid_per_ibui = fullbuid / mannfjoldi * 1000) |> 
    group_by(sveitarfelag) |> 
    mutate(aukning = fullbuid_per_ibui / fullbuid_per_ibui[ar == min(ar)] - 1) |> 
    ungroup() |> 
    filter(ar == max(ar)) |> 
    mutate(label = ifelse(ar == max(ar), sveitarfelag, NA_character_),
           x = ar,
           y = aukning,
           y = case_when(sveitarfelag == "Mosfellsbær" ~ y ,
                         sveitarfelag == "Kópavogsbær" ~ y - 0.003,
                         sveitarfelag == "Garðabær" ~ y,
                         sveitarfelag == "Reykjavíkurborg" ~ y + 0.004,
                         sveitarfelag == "Hafnarfjarðarkaupstaður" ~ y,
                         sveitarfelag == "Seltjarnarnesbær" ~ y,
                         TRUE ~ y)) |> 
    mutate(sveitarfelag1 = fct_reorder(sveitarfelag, aukning))

p <- plot_dat |> 
    ggplot(aes(sveitarfelag1, aukning)) +
    geom_hline(yintercept = 0, lty = 2, alpha = 0.5) +
    geom_col(aes(fill = sveitarfelag)) +
    geom_rangeframe() +
    scale_y_continuous(labels = label_percent(),
                       breaks = c(plot_dat$aukning),
                       expand = expansion(mult = 0.01)) +
    scale_fill_brewer(type = "qual", palette = "Dark2") +
    theme_tufte() +
    theme(legend.position = "none",
          axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1)) +
    labs(x = NULL,
         y = NULL,
         title = "Breyting í fjölda fasteigna á höfðatölu í sveitarfélögum höfuðborgarsvæðisins (2018 - 2022)",
         caption = "Kóði og gögn: https://github.com/bgautijonsson/arsreikningar_sveitarfelaga")

p

ggsave(plot = p,
       filename = "fasteignir_a_mannfjolda_hlutf_aukning_2018_cols.png",
       width = 8, height = 0.5 * 8, scale = 1.3, bg = "white")
```

#### Hrein

```{r, fig.asp = 0.5, fig.width = 10, out.width = "100%"}
plot_dat_alls <- d |> 
    filter(ar >= 2018) |> 
    group_by(ar) |> 
    summarise(fullbuid = sum(fullbuid),
              mannfjoldi = sum(mannfjoldi),
              .groups = "drop") |> 
    mutate(fullbuid_per_ibui = fullbuid / mannfjoldi * 1000,
           aukning = fullbuid_per_ibui - fullbuid_per_ibui[ar == min(ar)],
           x = ar,
           y = aukning - 0.001,
           label = "Höfuðborgarsvæðið")

plot_dat <-  d |> 
    filter(ar >= 2018) |> 
    mutate(fullbuid_per_ibui = fullbuid / mannfjoldi * 1000) |> 
    group_by(sveitarfelag) |> 
    mutate(aukning = fullbuid_per_ibui - fullbuid_per_ibui[ar == min(ar)]) |> 
    ungroup() |> 
    mutate(label = ifelse(ar == max(ar), sveitarfelag, NA_character_),
           x = ar,
           y = aukning,
           y = case_when(sveitarfelag == "Mosfellsbær" ~ y ,
                         sveitarfelag == "Kópavogsbær" ~ y - 0.015,
                         sveitarfelag == "Garðabær" ~ y,
                         sveitarfelag == "Reykjavíkurborg" ~ y + 0.001,
                         sveitarfelag == "Hafnarfjarðarkaupstaður" ~ y,
                         sveitarfelag == "Seltjarnarnesbær" ~ y,
                         TRUE ~ y))

p <- plot_dat |> 
    ggplot(aes(ar, aukning)) +
    # geom_line(data = plot_dat_alls, col = "grey50") +
    # geom_point(data = plot_dat_alls, col = "grey50") +
    # geom_text(data = plot_dat_alls |>  filter(ar == max(ar)),
    #           aes(label = label, x = x, y = y), col = "grey50", nudge_x = 0.05, hjust = 0, size = 4) +
    geom_hline(yintercept = 0, lty = 2, alpha = 0.5) +
    geom_line(aes(col = sveitarfelag)) +
    geom_point(aes(col = sveitarfelag)) +
    geom_text(data = plot_dat |> group_by(sveitarfelag) |> filter(ar == max(ar)),
              aes(label = label, x = x, y = y, col = label), nudge_x = 0.05, hjust = 0, size = 4) +
    geom_rangeframe() +
    scale_x_continuous(limits = c(2018, 2022.75),
                       breaks = 2010:2022) +
    scale_y_continuous(labels = label_number(),
                  breaks = c(range(plot_dat$aukning), -20, 0)) +
    scale_colour_brewer(type = "qual", palette = "Dark2") +
    theme_tufte() +
    theme(legend.position = "none") +
    labs(x = NULL,
         y = NULL,
         title = "Breyting á fjölda fasteigna á 1.000 íbúa í sveitarfélögum höfuðborgarsvæðisins (2018 - 2022)",
         caption = "Kóði og gögn: https://github.com/bgautijonsson/fasteignafjoldi")

p

ggsave(plot = p,
       filename = "fasteignir_a_mannfjolda_aukning_2018.png",
       width = 8, height = 0.5 * 8, scale = 1.3, bg = "white")
```


```{r, fig.asp = 0.5, fig.width = 10, out.width = "100%"}
plot_dat_alls <- d |> 
    filter(ar >= 2018) |> 
    group_by(ar) |> 
    summarise(fullbuid = sum(fullbuid),
              mannfjoldi = sum(mannfjoldi),
              .groups = "drop") |> 
    mutate(fullbuid_per_ibui = fullbuid / mannfjoldi * 1000,
           aukning = fullbuid_per_ibui / fullbuid_per_ibui[ar == min(ar)],
           x = ar,
           y = aukning - 0.001,
           label = "Höfuðborgarsvæðið",
           sveitarfelag = label) |> 
    filter(ar == max(ar))

plot_dat <-  d |> 
    filter(ar >= 2018) |> 
    mutate(fullbuid_per_ibui = fullbuid / mannfjoldi * 1000) |> 
    group_by(sveitarfelag) |> 
    mutate(aukning = fullbuid_per_ibui - fullbuid_per_ibui[ar == min(ar)]) |> 
    ungroup() |> 
    filter(ar == max(ar)) |> 
    mutate(label = ifelse(ar == max(ar), sveitarfelag, NA_character_),
           x = ar,
           y = aukning,
           y = case_when(sveitarfelag == "Mosfellsbær" ~ y ,
                         sveitarfelag == "Kópavogsbær" ~ y - 0.003,
                         sveitarfelag == "Garðabær" ~ y,
                         sveitarfelag == "Reykjavíkurborg" ~ y + 0.004,
                         sveitarfelag == "Hafnarfjarðarkaupstaður" ~ y,
                         sveitarfelag == "Seltjarnarnesbær" ~ y,
                         TRUE ~ y)) |> 
    mutate(sveitarfelag1 = fct_reorder(sveitarfelag, aukning))

p <- plot_dat |> 
    ggplot(aes(sveitarfelag1, aukning)) +
    geom_hline(yintercept = 0, lty = 2, alpha = 0.5) +
    geom_col(aes(fill = sveitarfelag)) +
    geom_rangeframe() +
    scale_y_continuous(labels = label_number(),
                       breaks = c(round(plot_dat$aukning))) +
    scale_fill_brewer(type = "qual", palette = "Dark2") +
    theme_tufte() +
    theme(legend.position = "none",
          axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1)) +
    labs(x = NULL,
         y = NULL,
         title = "Breyting í fjölda fasteigna á höfðatölu í sveitarfélögum höfuðborgarsvæðisins (2018 - 2022)",
         caption = "Kóði og gögn: https://github.com/bgautijonsson/arsreikningar_sveitarfelaga")

p

ggsave(plot = p,
       filename = "fasteignir_a_mannfjolda_aukning_2018_cols.png",
       width = 8, height = 0.5 * 8, scale = 1.3, bg = "white")
```